#!/bin/sh
FPK_EXEC=/usr/bin/slock; export FPK_EXEC
test -x $FPK_EXEC || { 
    echo "Executable '$FPK_EXEC' not present!" >/dev/stderr
    exit 1
}
which fprintkill >/dev/null || exec $FPK_EXEC "$@"
FPK_ARGS=
n=2
while eval "test -n \"\$$n\""; do
    eval "FPK_ARGS=\"$FPK_ARGS '\$$n'\""
    n=$((n+1))
done
export FPK_ARGS
exec fprintkill
