#!/bin/sh
getkey() {
    [ -n "$1" ] && {
	P=$1; shift
	printf "\n$P " "$@"
    }
    if which stty >/dev/null; then
        old_tty_settings=$(stty -g) # Save old settings
        stty -icanon
        k=$(head -c1)
        stty "$old_tty_settings"    # Restore old settings
    else
        read k
        k=$(printf "%s" "$k" | head -c1)
    fi
}
if [ "$USER" = 'root' ]; then
    USERS=root
    [ -n "$SUDO_USER" ] && USERS="$SUDO_USER root"
else
    USERS="root $USER"
fi
show_fingerprints() {
    clear; echo
    local u=''
    for u in $USERS; do fprintd-list $u | grep -E '[Uu]ser\s|: (left|right)-'; echo; done
}

k=''
while [ -z "$k" ] ; do
    show_fingerprints
    getkey "\nThe above fingerprints are currently enrolled for $USERS.\n\nWhat do you want to do?\n%s\n%s\n%s\n%s\n" \
	   "Q. I'm done!" \
	   "1. Refresh all of  $USER's enrolled fingerprints?" \
	   "2. Delete all of $USER's finger prints and enroll new ones?" \
	   "3. Enroll new / refresh selected finger print(s) for user $USER?"
    case "$k" in
	q|Q) break ;;
	1)
	    FINGERPRINTS=$(fprintd-list $USER | grep -oE '[0-9]: (right|left-).*' | cut -d' ' -f2)
	    if [ -n "$FINGERPRINTS" ]; then
		printf "\n\nEnrolling the following fingerprints for user '%s':\n" "$USER"
	    else
		printf "\n\nNo fingerprints found for user '%s'.\n" "$USER"
	    fi
	    for f in $FINGERPRINTS; do
		printf "  %s\n" "$f"
		sudo fprintd-enroll -f $f $USER || {
		    getkey "Failed to enroll $f for user $USER.\nPress any key to continue."
		}
		sleep 1
	    done
	    getkey "Press any key to get back to the main menu."
	    k=''
	    ;;
	2|3)
	    [ "$k" = '2' ] && fprintd-delete $USER
	    k=''
	    while [ "$k" != 'q' -a "$k" != 'Q' ]; do
		show_fingerprints
		getkey "Which finger do you want to enroll for user $USER?\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n" \
		       "Q. I'm done enrolling new fingerprints for user $USER." \
		       "0. left-thumb" \
		       "1. left-index-finger" \
		       "2. left-middle-finger" \
		       "3. left-ring-finger" \
		       "4. left-little-finger" \
		       "5. right-thumb" \
		       "6. right-index-finger" \
		       "7. right-middle-finger" \
		       "8. right-ring-finger" \
		       "9. right-little-finger"
		case "$k" in
		    [0-9])
			case "$k" in
			    0) f='left-thumb' ;;
			    1) f='left-index-finger' ;;
			    2) f='left-middle-finger' ;;
			    3) f='left-ring-finger' ;;
			    4) f='left-little-finger' ;;
			    5) f='right-thumb' ;;
			    6) f='right-index-finger' ;;
			    7) f='right-middle-finger' ;;
			    8) f='right-ring-finger' ;;
			    9) f='right-little-finger' ;;
			esac
			sudo fprintd-enroll -f $f $USER || {
			    getkey "Failed to enroll $f for user $USER.\nPress any key to continue."
			}
			sleep 1
			;;
		    q|Q)
			;;
		    *)
			k=''    
			;;
		esac
	    done
	    k=''
	    ;;
	*)
	    k=''
	    ;;
    esac
done
show_fingerprints
exit 0
